"""Phase A: Supervised training of GNN on ILP optimal labels.

Trains a SupervisedGNN (GATv2Backbone + sigmoid classifier) on binary edge
labels produced by the ILP solver.  Uses weighted BCE loss so that edges
carrying higher traffic receive larger gradient signal.

Each PyG Data object has a different number of candidate edges, so we do
per-sample forward passes and accumulate the loss (no true batching).
"""

import os
import json
import random
import numpy as np
import torch
import torch.nn.functional as F

from .model_gat import GATv2Backbone, SupervisedGNN
from .generate_dataset import load_dataset
from . import config


# ---------------------------------------------------------------------------
# Evaluation
# ---------------------------------------------------------------------------

def evaluate_supervised(model, test_data, device="cpu"):
    """Compute accuracy, precision, recall, F1 on test set."""
    model.eval()
    all_preds, all_labels = [], []
    total_loss = 0.0

    with torch.no_grad():
        for data in test_data:
            data = data.to(device)
            probs = model(data)
            loss = F.binary_cross_entropy(probs, data.edge_labels)
            total_loss += loss.item()
            preds = (probs > 0.5).float()
            all_preds.append(preds.cpu())
            all_labels.append(data.edge_labels.cpu())

    all_preds = torch.cat(all_preds).numpy()
    all_labels = torch.cat(all_labels).numpy()

    n_total = len(all_labels)
    n_pos = int(all_labels.sum())
    n_neg = n_total - n_pos
    n_tp = int((all_preds * all_labels).sum())
    n_fp = int((all_preds * (1 - all_labels)).sum())
    n_fn = int(((1 - all_preds) * all_labels).sum())

    accuracy = (all_preds == all_labels).mean()
    precision = n_tp / max(n_tp + n_fp, 1)
    recall = n_tp / max(n_tp + n_fn, 1)
    f1 = 2 * precision * recall / max(precision + recall, 1e-8)
    avg_loss = total_loss / max(len(test_data), 1)

    return {
        "loss": avg_loss,
        "accuracy": float(accuracy),
        "f1": float(f1),
        "precision": float(precision),
        "recall": float(recall),
        "n_total": n_total,
        "n_pos": n_pos,
        "n_neg": n_neg,
    }


# ---------------------------------------------------------------------------
# Training
# ---------------------------------------------------------------------------

def train_supervised(
    dataset_dir="data/ilp_dataset",
    hidden=64,
    heads=4,
    n_layers=3,
    lr=1e-3,
    epochs=100,
    batch_size=32,
    train_ratio=0.8,
    early_stop_patience=15,
    device="cpu",
    output_dir="results/phase_a",
):
    """Train SupervisedGNN on ILP labels.

    Args:
        dataset_dir: path to dataset generated by generate_dataset.py
        hidden: hidden dimension of GATv2 backbone
        heads: number of attention heads
        n_layers: number of GATv2 layers
        lr: learning rate
        epochs: max training epochs
        batch_size: mini-batch size (number of samples per gradient step)
        train_ratio: fraction of data used for training
        early_stop_patience: stop if test loss doesn't improve for this many
            epochs
        device: 'cpu' or 'cuda'
        output_dir: directory to save model checkpoints and curves

    Returns:
        result dict with best metrics and file paths
    """
    os.makedirs(output_dir, exist_ok=True)

    # 1. Load dataset
    print(f"Loading dataset from {dataset_dir} ...")
    train_data, test_data = load_dataset(dataset_dir, train_ratio)
    print(f"  train: {len(train_data)} samples, test: {len(test_data)} samples")

    if not train_data:
        raise ValueError("No training data loaded. Check dataset_dir.")

    # 2. Build model
    backbone = GATv2Backbone(
        hidden_dim=hidden,
        n_heads=heads,
        n_layers=n_layers,
    )
    model = SupervisedGNN(backbone).to(device)
    print(f"  model params: {sum(p.numel() for p in model.parameters()):,}")

    optimizer = torch.optim.Adam(model.parameters(), lr=lr)

    # 3. Training loop
    best_test_loss = float("inf")
    best_epoch = 0
    patience_counter = 0
    history = []

    for epoch in range(1, epochs + 1):
        model.train()
        random.shuffle(train_data)

        epoch_loss = 0.0
        n_samples = 0

        # Mini-batch loop (each sample has different edge count → per-sample fwd)
        for batch_start in range(0, len(train_data), batch_size):
            batch = train_data[batch_start : batch_start + batch_size]

            optimizer.zero_grad()
            batch_loss = torch.tensor(0.0, device=device)

            for data in batch:
                data = data.to(device)
                probs = model(data)  # (E,)

                # Normalise edge weights so mean = 1
                w = data.edge_weights
                w = w / (w.mean() + 1e-8)

                loss = F.binary_cross_entropy(probs, data.edge_labels, weight=w)
                batch_loss = batch_loss + loss

            # Average over samples in the mini-batch
            batch_loss = batch_loss / len(batch)
            batch_loss.backward()
            optimizer.step()

            epoch_loss += batch_loss.item() * len(batch)
            n_samples += len(batch)

        avg_train_loss = epoch_loss / max(n_samples, 1)

        # Evaluate on test set
        test_metrics = evaluate_supervised(model, test_data, device)

        history.append({
            "epoch": epoch,
            "train_loss": avg_train_loss,
            **test_metrics,
        })

        if epoch % 10 == 1 or epoch == epochs:
            print(
                f"  epoch {epoch:3d}/{epochs}  "
                f"train_loss={avg_train_loss:.4f}  "
                f"test_loss={test_metrics['loss']:.4f}  "
                f"acc={test_metrics['accuracy']:.4f}  "
                f"f1={test_metrics['f1']:.4f}"
            )

        # Early stopping on test loss
        if test_metrics["loss"] < best_test_loss:
            best_test_loss = test_metrics["loss"]
            best_epoch = epoch
            patience_counter = 0
            # Save best model
            best_path = os.path.join(output_dir, "phase_a_best.pt")
            torch.save(
                {
                    "backbone": model.backbone.state_dict(),
                    "full": model.state_dict(),
                    "epoch": epoch,
                    "test_loss": best_test_loss,
                },
                best_path,
            )
        else:
            patience_counter += 1
            if patience_counter >= early_stop_patience:
                print(f"  Early stopping at epoch {epoch} (best was {best_epoch})")
                break

    # Save final model
    final_path = os.path.join(output_dir, "phase_a_final.pt")
    torch.save(
        {
            "backbone": model.backbone.state_dict(),
            "full": model.state_dict(),
            "epoch": epoch,
            "test_loss": test_metrics["loss"],
        },
        final_path,
    )

    # Save training curves
    curves_path = os.path.join(output_dir, "training_curves.json")
    with open(curves_path, "w") as f:
        json.dump(history, f, indent=2)

    # Final evaluation with best model
    ckpt = torch.load(best_path, weights_only=False, map_location=device)
    model.load_state_dict(ckpt["full"])
    best_metrics = evaluate_supervised(model, test_data, device)

    result = {
        "best_epoch": best_epoch,
        "best_test_loss": best_test_loss,
        "best_accuracy": best_metrics["accuracy"],
        "best_f1": best_metrics["f1"],
        "best_precision": best_metrics["precision"],
        "best_recall": best_metrics["recall"],
        "total_epochs": epoch,
        "best_model_path": best_path,
        "final_model_path": final_path,
        "curves_path": curves_path,
    }
    print(f"Training complete: {result}")
    return result
